import Header from "@/components/Header";
import "./globals.css";
export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es">
      <body>
        <section className="container">
          <Header title={"Cargo Orders"} subHeader={true} funct={null}/>
          {children}
        </section>
      </body>
    </html>
  );
}
